#include <string>
#include <vector>
#include <chrono>
#include <iostream>


std::vector<std::string> test_data = {"jqmknamokpmtavoxvfwxvzgwrmohjuyldjfsjbftnoirbgajjciurynqivkniqyenanhkdahsjkxsiowyxenibnaodavgvkvbcexakbjuljbvmdlaavqlpihvpwaipekvuxoeqvueyqtlbftzkyzyugkzygotbkdmlgkwjwvjwjhhqzmdaqhgfxekogkvaqsdeifubvbplklsludrntmemrygxqhpvvcjeigbmwsapivrksllvdcyzuviu","bmqlkudnzeviaeqvquzmbappzksbvauwxuqfpwkfvvkbeidgcmqleqevnylhxubyvjdhqkayngerithocfvjkkyudcwllguvwjhbvjopnkvxhljddjgfjryknyuiomtkmhxritjadkeixazaiuqgyjsyvyaiisfvqigfilorpkpmvlvamxvjmsvmatobhxhwjnbblzjosxsatqkpwwvalyodkrkagznbbnslvjnevodcugeggktiaemwro","riellsqyeiuqzjpapwvmpqyezartjhflvjwuqkvbfjuydbitkwypnnbksjbtjbaqiuazlewvdwbxevlndxpilqgvmoyavavgaomyiokxuajyhagixcjdeisrvvakfsjknqehkhvkvmnmwjgmevqhrnkpawlstkxfvoyudaznivhgkbbdpditucrhtqehbxiagraxuikldnzlukvxfnkkjgmlksmsgoqvdmebvjgyclboomvwvfyogojucz","zvqrvglckdqebxpuclgbizragbnwrwnabpqxuxadkuwdgxecmsvejibnjheqkraxssuqoywromyhhzvklkdjxiaeihimkkofdungkmskfjujkymvvvkdaygcnlymjyvvkxywzanqikplkwmephuafavyfveieobqbhjnaoyjogxgntbqsddiftihqteieomfjvgylvvoqvbjptupkzwtjnlijslbgkmiuvhlaavtvdljbpwsoulvazvarm","olwrmjdvzgnsinneshaqfwqbmqezmmbvvykbdqqegntsxoyyktwbxnbqvbhaubkmgtkjqjugkaelribjeaxaciepkrbfdhjqmvnlevykdsnrvujluvaxyykuphoyoakmaxwobzpivilvtoifealvanjovtgkjlqjswrjpvfvhkvilkrtmwikigpmdkiogzqygycigaxvdvzxxpadudnudylujjhmhfkclcavavpvswjlubeioukwfhgesz","ivejavaxvbmvplklwgyawesimhovskbhivsinnobrkhddetfamkhkdkoivxcajsgtxezatcfevjlbqwbkxidqyyyknkykujkiwvaovidjzmoouqnwrmpibrpmmwgnkbvnsjjfymdgyqlalnfvyicvboungbjmuuhfghtjbsuaqlzateyvregldevrkxlkuvboyepkvoxxcamgdfsjqtpguuqgaewlazvqrvuzzqjjhqilipwpxkhjvland","pohyyliinotagjkbbdrdvxgkhqmvbnsjuivtjrzzjdxenbvlndnakptjzfoixifmujdbavnuwvxsgmefkjqsmcgqwpidoilulcizeojklwbsuhpaotkiileujkkrvbblyzecwyjedphjokahaaeahwqqalkqmfmfvvuvqlxtbmrvahyyidibvkvfsqxptvezxyxgnoqwahmdskuajvkogklucagggevkqanjvmvvmrsgkrvupynwweblyy","ieonegohvqdijnjwziloffltzumageoynbiyureqtezkblpbdvmvbacijbwfenzdgoyvqvsyckhaoksmbkkrjmjjynskmglfvoskbwtxtaiwlkdwyabmjvhjphkuayreqhakvghmztcupximpxprqbejgxbjuhfiudwjvlsilpaegmtqvsrqanuvkvdlasvbknhrwlakxiqcvvlaajfzxvkdiagnvkdqgdyqkyuuvwupoxmiejlvgxvyon","gabjzebcibeprlntvmlvhdowqsutwfcobbjyvgktwqdhbukauqlhvvxvkvfblkvckiwvkunjjiogwupmfstkrasnpgjeqawvlyzyokkveqlkqvdkjegajyzhvybrmzoippatpwfmvveoxijighkrnlgqvadjiryqmxonepkuvukgauarbwlvoamlxixinjytmbaokylauvvlgzmqhfbiycyfuedjnsqjmhsazaskenmeidgidsxdhjxxnd","wdjbpfcewhuvjfqdyqeomfptuqxdtjiwwryjalbitkijkhkajglxgawkvesuydghfhxzirzgydyabooitxobgldmsfchxinipvaessorcxayxbdvvhnouqtkvbuyneywdzldhvkqsuwingpugklemgmvacrkekvpvnaulablvaumaabjvrevjovvrjtlvmifxnyneapwupvjnkmibzqvhkqbqykzavqlgkbqvljizesokmsjlmmoknjigk","gkgvvevavbufeqpyllaomzscsnirdrekaxwsttyaqkerxkwajvkfyvncomhzlukenknkwcbhabhpjgvramogpiauglkxbaithsyuijrijlbkdeopjyxwiufoqupldkkzxwvqktqsqjogbbngqvmphexqyigvdnmxdkdmzujyveuksziavmnhnvtovrmdavckqbwtgbvaiflabuvdjjbqvzlidjlfynejlushwamiyvvjjmlyefgxhiwpoo","kgsvaulqzodwgbgtjxhiaqgqskbbohditezlgiixzumrjdvwkedwvpazifmgxvkpbuevpbvfveykqngjrasvxrbiqbhqclevvnvnfqqtkggiwrirqtnonkknkcylvaqvjulkmsmhfslbwdvjpwmgakneuotdyjovmbvaszypvlajajjbcaauyltaewdikvnomyixmviyaapxvcmldfbjyekzjjiwkuusefuxooyhnkhkmydrxhluoljehp","zwrhbdinbkaikqotbsbipdqkfmeyfjsgqbhkirvwlcvrfsuomxkekxlyjrovknyveaqxhhlxvppvsykbnpiitdwjklvteomcziqwaaelavalbpvjugdrvdovkmgwhkwqveafapojbyvjrnmsekwgukmiabtazvhqexoukqhjktojhodgclljeeuvgysalzivzyguftuxnsxayfivwzjmyaajbinlvcnxdbjdnqipyknmuvvmuujlgggmdq","xhgcsxeuqvqhmegcjbqdsjvrpzvuokyzvjnqdfaajgtafbvwpebvkhmgyixolkwroodtnvmkcvtnuvejkyqtgyyjardvrpbdvasiowkjkkulomldlxnuayewupgpwozqxvlfpnanexbuiqmtjfbjkwohmxdduoxmknvvseinlkkiyyrfiluiazrajqvhvkswidspvmqbblstelabivjmemwakuahkvjzgyeialvhlqgbgjzyaihbgicfnk","akyzdjdzztxvuduxkqklievwnfbozdxaojbdklpefiaawobamqezvqjpeuskgmrrlyaquftcgribbmkpdviamegektoblvevjrvvtnukmvwpgmvlakexynnsbahgvwobsejivgblljhikxduxrvacqqdkpighfhkyugkkysjlgmtmsljjosihvynmcmlcaqsnhvfjbxxeqtprquvywnydkpqvkagavwjnwyfnhaziijywohjuuovlviiob","aplgbwviabkgbnqnwrxgsqwevyhaeddxdvijjtqiutkvdvnbsplsjsouipsjvhcbydopgkkonmadgmmbynvlxekownixavuyybkvufkkkfibbzvvmkbcrhkjilkergkmaywqiuhrewamzjmvzyhholhajlljvzxkedvqyeafxlhglouqpdmazikrqusvgffmzavcntyjckvvqiejgqajtwdueaixwtjqfnjenvpbrgvuaospltmuiyxool","ikaiaihivqfvwqixouhzwkaidlvksgyhdnrlzyvbqzabwuvjelpnakqnevkuaalejyhbymsxlsnpqxynvvlhhikqctrswduvvvfqjmmyhoaoxwpiaqdueklgsdosnbvkbmjdmcawfregiuikbvbfjokjylkugqjxesgjigvpvwouggajtlobrmiennmxkpdoreftkokvxhjbyemlakwjgmgavdvrtbztcdbyvvzujxtzcepnfjmyalkupq","ueevkksbxmxvdutenusguauvloqdzonkrkqyvrlaithgeluavkhpxqaaaoysrpezajvkmpdatuvqyksmhvapkjnmgxvuyuxjlbwkrbfvkwlqrtepbbjzyovfkqveifajygqcinbfgdeasmzjaxibliqogbvwndhfgiakygabxdhovmghqskmyvzpuivwqknmwlihnkzojpyjsjrjvkclmwinwgjljccljoeilndtbovhdxydmwbvtvifei","zausjriawclxmheuujynfiabieqrvqdpibykxztgdxkboakhhimwwhvhqjipbwuglnlugrigojkynrvpffekiblduyzvanrhjgajskejsqeomuyxbgjynssnbmklejbpvkktvanqoxcuvfyeakhkdodgkqpieoitavwmavrgqxvtdjmhwpcgyvoqisbuvykebllunvvjxlyfclaqafavdtldzqewvvvoktsklnjdzmmxvabmvomzigpkjw","egmbkbxacjymangbysmukgimajokpnqqdhiolyajahnzpkjeikoumvjgmafazxdkqcwzvlrdzuqvslwurtbbslecumwnmguxngvobinkkhhmwgpxawevlveejrydnivvbgkfhblijcatjjwjwadupxqsiveqtsqofpldeykjiywlarfdypiktprvqkuvuqvbvsfodqknvvlkijojzbioxheevxadzhvvamtotnaglyvyxgisublvfkhkry","ieonegohvqdijnjwziloffwtzumageoynbiyureqtezkblpbdvmvbacijblfenzdgoyvqvsyckhaoksmbkkrjmjjynskmglfvoskbwtxbaiwlkdwyatmjvhjphkuayreqhakvghmztcupximpxprqbejwxbjuhfiudwjvlsilpaegmtqvsrqanuvkvdlasvbknhrglakxiqcvvlaajfzxvkdiagnvkdqgdyqkyuuvwupoxmiejlvgxvyon","svarvvkgudabhnjazoiffpmqwdekdwftwkcisvkbkyusjuqglbnyuslyauqiwqmyoniexvoqivlvkbpeivvfgrwhvvajnyakskktzvdlroaevjbdxvluaianwmkdvljoebpygkjzelasobmgptyjdanvqluuqgmpxhelucxxyefvbgcktvaiztnhyoibkoqwqxdnzjjogejvwxymhmlhiurcriljnxjskjkrvztqempmpbgkfhbaigdahm","kirckfiiujesbjkqbjthvamlmylartnaumuxjwaaqlwnrqqdvmanvbpgejxvdxyykofrhlngzkcwbquiiucovkjioboideggkqsnmkkdaggsavibwzfdmoluktpybvhgfxehuojbmjcivehnwvlsiekjeaukdvzwaeyyvpdmrjfxqawnajyoeqgiddsytvwyzpangvklvbjtkhvusovyohrvkbkhvjitvxxqpgslmlbmellpquzpnafxvz","hadqkesxllraekarnegwjqoduaawrpokvusqcauylyvrysnlvlkqxwkxvpvpieuvvnjvjgvjtcuqdxivozitieqdjdnexhbeaclvphlaqmwmsxxjljfbfiogkkhkjtzxyvakmnofgmhuvsyabbmpjdesmbbhkzhjbfkndmyjbkkqavjvdbfgluvivgiealimwpzqsfgoivzyjunyowievipvcuytdnlrwqoatzikbbahwrmmgngkuytgok","mvmbmhdqzrvxdubiajqgohcggpjmkhytvfjakjokfdvimlueplyyldarrfdinvhwjalafgcmwiwhgzxnnzaliivvgvbeqvjetuvdfasaeewklqhyivebzetgjohmotvmvbvbgvofiiezumkjdkxjknrcjopsqxrypztibqikbyrsokvoykpmyugodqkwleaxyvugakkbqjcxnwvhpxxavwdapsuinjetljwlanyqlnuaubkslvkqskubns","olwrmjdvzgnsinneshaqfwqbmqezmmbvvykbdqqegntsxoyyktwbxnbqvbhaubkmgtkjqjugkaelribjeaxaciepkrbfdhjqmvnlevykdsnrvujluvaxyykuphoyoakmaxwobzpivilvtoifealvanjovtgkjlqjswrjpvfvhkvilkrtmwikigpmdkiogzvygycigaxvdvzxxpadudnudylujjhmhfkclcaqavpvswjlubeioukwfhgesz","xhgcsxeuqvqhdegcjbqdsjvrpzvuokyzvjnqdfaajgtafbvwpebvkhmgyixolkwroodtnvmkcvtnuvejkyqtgyyjardvrpbdvasiowkjkkulomlmlxnuayewupgpwozqxvlfpnanexbuiqmtjfbjkwohmxdduoxmknvvseinlkkiyyrfiluiazrajqvhvkswidspvmqbblstelabivjmemwakuahkvjzgyeialvhlqgbgjzyaihbgicfnk","wqijnqulcanqvuewodakbvsfxwikxoxanltjdiogybkcrvhojaqybfhlkgfejyjvzqwpivledsstlgjplkkawtavpncjvbmetvxkdgwkmbmblvhgusvlxrkboymmvjpkuwburumjainunnrprrlcvtgykqsquhdaqzekkngjgoxbvekihmiyyivzkvueehygabfvpwosikiidzjfvjxlldvjxhpqteiymhugdnamqzdveomaazsfbovaya","kxbggdwqihopvldajvbmmznolsdvujoovivzmnjfyuejjdszlyhoplaainckjkyznajnznqkdvvauuyswykypfaetvrgjvsdzxiruibplgidkfawyvkfeubwhvqrgkkvfmtvjtwememqhmgaiubsxpfegakbtuxpxrojjmgrqtldmqlbkchklixispsvanhuqokbkbbgbmvqqhcywnveaytgeuyalvvvnxqoiikevlkclawewohadjrijx","lyykqqzwqvgmajbzobfmrtfprnarnlveeljibbxgqwhdugknjdpqvnpkeekvdiygxppitdgvxvjqyejgkjihzdoiubsqhatlqyeakladufcwzbyzycvpcnmbuiujlzvfadhybljwiulnaamkheoojegshbdivkvasnyudukogamxbisiwvinoavwkvwyxvshirekjupkxfmvjmjsggxrkrlvvmovqbkkkmttjaaoltcnohvwfvmelquasx","pinndzmotucqyalkewodvujphdyqybekvkafnkiueovlmmuevqbhxgvmxvwkgxcougqwgjipaqlefsayamrmbabkkjhikpixvsstggiwktfiiiixotssvzwzjsvbsgakdawhlzyjmgjnuyjbvpnuxatrloupoeyerlnbjkjmwrqakzndjekmavhkgxcyybvvldrepcfaovjvqkdbjvqquhyflmzdaovifajlwnvtbhgkhivnlxlubqervd","dzdozvwjsaijelefqsgyapusvmpnojjbzojtienlkaqbefjeuyxkvruymgvnllmkigqafwirwkmfnndikkrvpkjebcibuvznwnmhzoiykoggauvmejiqabackahyxkafkvaegbwzvqklurmxagddjwkpwqvibhqtxxvuvshgltsddsyvxyvotbdalqscuxvitbfrbovnumhjkhiwthyaycvvqiybkupllrmgedojmxlpjqhvnokapegjvl","fpykyddtjjibbakvqjdfvvknyitauoqyckkhcanehqgianrickgywikeyoabkamozpwqfnbmivnwpevbqvjuudezptxpushgglmpskvvemukkvmgzxgdfklnymrivjemlsgmydlxabnjhslqgmtuuakungzvgvxwajqyixqhiljmilkwbulbxhqpiywrofdjewadsjkbrvszsqaobzlnfxtohrhxvbukoleijvreatjcevjowalvavdovv","ueevkksbxmxvdutenusguauvloqdzonkrkqyvrlaithgeluavkhpxqaaaoysrpezajvkmpdatuvqykswhvapkjnmgxvuyuxjlbwkrbfvkwlqrtepbbjzyovfkqveifajygqcinbfgdeasmzjaxibliqogbvmndhfgiakygabxdhovmghqskmyvzpuivwqknmwlihnkzojpyjsjrjvkclmwinwgjljccljoeilndtbovhdxydmwbvtvifei","uqijsmtvriacoqfdlotnpbrokmkehnleqqkgeuvbvmjwpvlglvtgdkwsbiivlxxmjcraebdjswdquinzyvfkogvhfhujwmfsdlyidunpyrvqaqlvilknzvkectskiwieijpxbyfoedyaugyvmwzeqvuwakjgnbepvejnowinhzukajmaaxymgvhzovdabqgamltxtkzhklbggapvfmybjqyuhbhsobjxolxukaikxvasvvayjkpkjcnrrd","wxvyqeidovwhvfscbgvylakunmtjsbnanepehfkkkvqmajaskmidphmzxpkbkgjxvtalkdsaupybtamcvrwkmrvqbkeojllrtpsigdhaqluueozjvsaajnayljqgzvbajlbknbykdzixegbnetivcrvbwaovejtfycddoynywvfouwlqkirkqeivahugyqvpziloxvgijbuudlnqymdulkkzmhohpjwrhvfnxvwfimqiuxgxigvjgoesmj","riellsqyeiuqzjpapwvmpqyezartjhflvjwuqkvbfjuydbitkwypnnbksjbtjbaqiuazlewvdwbxevlndxpmlqgvmoyavavgaomyiokxuajyhagixcjdeisrvvakfsjknqehkhvkvmniwjgmevqhrnkpawlstkxfvoyudaznivhgkbbdpditucrhtqehbxiagraxuikldnzlukvxfnkkjgmlksmsgoqvdmebvjgyclboomvwvfyogojucz","ojwykmncocsubpameljxceikiqoyiulqluvjxyfztkrxnmeljvonndwalggaivhbbkotliuvnbvabpvdbokesqvvgiwojyhajtniajbkzvurmskzcplyfpiayfadklqdndbgkvmhgvkupuktvmguhkljxukfojwrvqagpvzygavrlhsuyeedtzmvkqejtavbjhlazyfwewfxysqxdqimrvmnbpvhwivqseqrbxmigdskkngihwadajxeoj","ivejavaxvbmvplklogyawesimhovskbhivsinnobrkhddetfamkhkdkoivxcajsgtxezatcfevjlbqwbkxidqyyyknkykujkiwvawvidjzmoouqnwrmpibrpmmwgnkbvnsjjfymdgyqlalnfvyicvboungbjmuuhfghtjbsuaqlzateyvregldevrkxlkuvboyepkvoxxcamgdfsjqtpguuqgaewlazvqrvuzzqjjhqilipwpxkhjvland","hadqkesxllraekarnegwjqoduaawrpowvusqcauylyvrysnlvlkqxwkxvpvpieuvvnjvjgvjtcuqdxivozitieqdjdnexhbeaclvphlaqmkmsxxjljfbfiogkkhkjtzxyvakmnofgmhuvsyabbmpjdesmbbhkzhjbfkndmyjbkkqavjvdbfgluvivgiealimwpzqsfgoivzyjunyowievipvcuytdnlrwqoatzikbbahwrmmgngkuytgok","kirckfiiujesbjkqbjthvamlvylartnaumuxjwaaqlwnrqqdvmanvbpgejxvdxyykofrhlngzkcwbquiiucovkjioboideggkqsnmkkdaggsavibwzfdmoluktpybvhgfxehuojbmjcivehnwvlsiekjeaukdvzwaeyyvpdmrjfxqawnajyoeqgiddsytvwyzpangvklvbjtkhmusovyohrvkbkhvjitvxxqpgslmlbmellpquzpnafxvz","ouijmmjiteeauugfxovoguwsdlibsrjtgbkbxehkiuahrirwvjsmwwvebypvmdmalkyvkkdynvqibbwxpkclyozeeegevatukmkdbqxewlyhvinolrhbalgsapvynftlqqpxnlfkclnvhhcpxgxknajbifyqzfjukizbosntgjjuohsqhkjyujcjoavvdqvwtnglaoivamvkgasybwmupkkrkjzvjmzgfidazyqvnrxdmqaplevdqvviad","dbtxpbqtbhkjgazvfiqvbmflasopmjibejdiuayizylxvrvxykqawrygjtlvshyaiwlbnuajzpzblrhigxedbmvlmveftggvhnfusveitvvvojelvznwfmuirkkbqmwakubekcxjqnfpknnoavauskueyavphcsyowqxlccdaeykptkiqdiueawvokolusqgkkvxkjbvoqdjmghnmdmjaggjwzjoykiqwravgdnmlokndjvyhiselhurxp","dbtxpbqtbhkjgazvfiqvbmflasopmjibewdiuayizylxvrvxykqawrygjtlvshyaiwlbnuajzpzblrhigxedbmvlmveftggvhnfusveitvvvojelvznwfmuirkkbqmjakubekcxjqnfpknnoavauskueyavphcsyowqxlccdaeykptkiqdiueawvokolusqgkkvxkjbvoqdjmghnmdmjaggjwzjoykiqwravgdnmlokndjvyhiselhurxp","ogjiviqmvgagejrvvzkokjoudnxilycihrsxvvvyeaykghpkmwtttjrsiwnekykjjbkmidvqwjfpvaouvoowoxaqywdivghqbkqyhgflvfhlpsbmvmjuhcczflqbgmneloyvnjzdxlzpnplxseticqlbxiuevkxnuikadzjgmaenzkuvjhuagqvmblybifybkawjwuqpaupshtdmeqdlbvfkektrvuagsrdnajlebbaaivnsykomxkrwad","akyzdjdzztxvuduxkqklievwnfbozdxaojbdklpefiaawobamqezvqjpeuskgmrrlyaquftcgribbmkpdviamegektoblvevjrvvtnukmvwpgmvlakexynnsbahgvwobsejivgbgljhikxduxrvacqqdkpighfhkyulkkysjlgmtmsljjosihvynmcmlcaqsnhvfjbxxeqtprquvywnydkpqvkagavwjnwyfnhaziijywohjuuovlviiob","ieonegohvqdijnjwziloffltzumageoynbiyureqtezkblpbdvmvbacijbwfenzdgoyvqvsyckhaoksmbkkrjmjjynskmglfvoskbwtxtaiwlkdwyabmjvhjphkuayreqhakvghmztcupximpxprqbejwxbjuhfiudwjvlsilpaegmtqvsrqanuvkvdlasvbknhrglakxiqcvvlaajfzxvkdiagnvkdqgdyqkyuuvwupoxmiejlvgxvyon","cnuwisaiyygvoldafjjskyvnnxocuqkrmleibiuxdcjgvuzxthbvoyxvzpnlzmemwbmlisfyogjpelpxejbbujywekojaknwlvrahnmaieeqkdhksovshqlaiinbyvvqewguatoapfqklkbhyvtwvknjudkqjodfktsvmajbfbxkvgmqvkheljvwurrldgzampamdgawzvkvbnfibqojeiazlvqtkgpyygvgushkuxhcpdqjdraiirtmxv","rabsbjkkutonymdmwlidwviymobvrvhkgvvejuqaroliatyktheuqviohkkcboznpnubnwkltbuzjfxvzjcjxspovpdkgkppxtdumbnapvnyeykqhqhglkcveqfshkhlglvevnzcmygdxjgavunweaiixvyjvqfkmvedvjlmxqjrumfjxjxoksvbvququbaanzdawqjodaeylratyzpissblfwiamkvgliwgigeigaiabwofeklhsydjmr","jxogakoubegqvlcdrmyikhizvevujigkqvlhmundekpoikwebglllmnwwkabyalsjvxpnugwdsfvqahmmuiyaazrmelnqyelevlnqvjvgkvgcovjewghaxoshrmbaytltiehqnjsmxjpxctklxjkkoxfwpbikqpzrvaguhrzamumvdbfbikcvzodhfvyyugtjznisiiuqovxbnuryvjnkidytkjvpvbeatwbkssdbydkdavjfpqqawajof","ieonegohvqdijnjwziloffltzumageoynbiyureqtezkblpbdvmvbacijbwfenzdgoyvqvsyckhaoksmbkkrjmjjynskmglfvoskbwtxbaiwlkdwyatmjvhjphkuayreqhakvghmztcupximpxprqbejwxbjuhfiudwjvlsilpaegmtqvsrqanuvkvdlasvbknhrglakxiqcvvlaajfzxvkdiagnvkdqgdyqkyuuvwupoxmiejlvgxvyon","xokkxyljivqbbiygkgmfndwvxuqblyamlwqosoqdrbeszrebkimgyvqytcdrvjkoiyrwvixeilstggjtvfvkbkmjkwlknkapumlhdzcvzhjzeaiigahhvasawhuqikeubavfnpbaoilorukmpftxeadfjjvpazxkacthvgvxxynjjravlidcjsousbzewmpqgehlvounvvpyvvieushqgfelnvlgumaajdbmounnwqkdwtqyjkdkpynmjb","uqijsmtvriacoqfdlotnpbrokmkehnleqqkgeuvkvmjwpvlglvtgdkwsbiivlxxmjcraebdjswdquinzyvfkogvhfhujwmfsdlyidunpyrvqaqlvilknzvkectskiwieijpxbyfoedyaugyvmwzeqvuwakjgnbepvejnowinhzukajmaaxymgvhzovdabqgamltxtkzhklbggapvfmybjqyuhbhsobjxolxubaikxvasvvayjkpkjcnrrd","ogjiviqmvgkgejrvvzkokjoudnxilycihrsxvvvyeaykghpkmwtttjrsiwnekykjjbkmidvqwjfpvaouvoowoxaqywdivghqbkqyhgflvfhlpsbmvmjuhcczflqbgmneloyvnjzdxlzpnplxseticqlbxiuevkxnuikadzjgmaenzkuvjhuagqvmblybifybkawjwuqpaupshtdmeqdlbvfkektrvuagsrdnajlebbaaivnsykomxarwad","xnvkvtideprgzhqgbyzaobfqkkzkykawzssheivkukpugmamjgqkeffmyvjxlcatwxkhvvaskdnqvvjkginkaauihwtvpaiipdnugxboyjsljmngbxioryliaglqquukerywwboirwfhejyfmorsybbdaxagclnoobvlmmkjhnjwpivbmxynnfeuluvdevsuvjvilvdzavekjvxyvwrqltdjjtjlqmcbhqboieaqpukpsacoddtzvlemhg","olwrmjdvzgnsinneshaqfwqbmqezrmbvvykbdqqegntsxoyyktwbxnbqvbhaubkmgtkjqjugkaelribjeaxaciepkmbfdhjqmvnlevykdsnrvujluvaxyykuphoyoakmaxwobzpivilvtoifealvanjovtgkjlqjswrjpvfvhkvilkrtmwikigpmdkiogzqygycigaxvdvzxxpadudnudylujjhmhfkclcavavpvswjlubeioukwfhgesz","riellsqyeiuqzjpapwvmpqyezartjhflvjwuqkvbfjuydbitkwypnnbksjbtjbaqiuazlewvdwbxevlndxpilqgvmoyavavgaomyiokxuajyhagixcjdezsrvvakfsjknqehkhvkvmnmwjgmevqhrnkpawlstkxfvoyudainivhgkbbdpditucrhtqehbxiagraxuikldnzlukvxfnkkjgmlksmsgoqvdmebvjgyclboomvwvfyogojucz","byvhyvyungwwwycoeunjojnjliifvxqqrkvgksidmsedjkzaxiekxwwluqjkuhcavldovgakvtvfjfakcxdwjpgdvymtmhojaahaomkytkebxsbpaquujxnfvevhmgmklagtmzrvekalhqeknjivssqbweifzxatvxvgqqikvjiphlbkzqjkvvgibyntvnmdujgprvfgoesrpmldsprnbzbldqyzobirbkaunpdmuleooiawcyuillhaby","dbtxpbqtbhkjgazvfiqvbmflasopmjibejdiuayizylxvrvxykqawrygjtlvshyaiwlbnuajzpzblrhigxedbmvlmveftggvhnfusveitvvvojelvznwfmuirkkbqmwakubekcxjqnfpknnoavauskueyavphcsyowqxlccdaeykptkiqdiueawvokolnsqgkkvxkjbvoqdjmghnmdmjaggjwzjoykiqwravgdnmlokudjvyhiselhurxp","ogjiviqmvgagejrvvzkokjoudnxilycihrsxvvvyeaykghpkmwtttjrsiwnekykjjbkmidvqwjfxvaouvoowoxaqywdivghqbkqyhgflvfhlpsbmvmjuhcczflqbgmneloyvnjzdxlzpnplxseticqlbxiuevkxnuikadzjgmaenzkuvjhuagqvmblybifybkawjwuqpaupshtdmeqdlbvfkektrvuagsrdnajlebbaaivnsykompkrwad","tektvgygkafuuybalsmvkubguhmaqqjmhjxivxuawlzokebamyucpqambqlswddoqyilhyasdimjnejwbvknaiytuklooqxmbvvwvzklpjizumgdwkmvvneoqgajhacwaxsbvzovhjxjfwirtdejynsfklarbhvkgpvizrrielyveklmnhvputqvipxaqfkbkeduboltjgvnbypvjrprjsvvlnedcidywggghfxnzsoeonkijxcikkdafq","wxvyqeidovwhvfscbgvylakunmtjsbnanepehfkkkvqmajaskmidphmzxpkbkgjxvtalkdsaupybtamcvrwkmrvqbkeojllrtpsigdhaqluueozjvsaajnayljqgzvbajlbknbykdzixegbnetivcrvbwayvejtfycddoynowvfouwlqkirkqeivahugyqvpziloxvgijbuudlnqymdulkkzmhohpjwrhvfnxvwfimqiuxgxigvjgoesmj","ueevkksbxmxvdutenusguauvloqdzonkrkqyvrlaithgeluavkhpxqaaaoysrpezajvkmpdatuvqyksmhvapkjnmgxvuyuxjlbwkrbfvkwlqrtepbbjzyovfkqvmifajygqcinbfgdeasmzjaxibliqogbvwndhfgiakygabxdhovmghqskmyvzpuivwqknmwlihnkzojpyjsjrjvkclewinwgjljccljoeilndtbovhdxydmwbvtvifei","ikaiaihivqfvwqixouhzwkaidlvksgyhdnrlzyvbqzabwuvjelpnakqnevkuaalejyhbymsxlsnpqxynvvlhhikqctrswduvmvfqjmmyhoaoxwpiaqdueklgsdosnbvkbmjdmcawfregiuikbvbfjokjylkugqjxesgjigvpvwouggajtlobrviennmxkpdoreftkokvxhjbyemlakwjgmgavdvrtbztcdbyvvzujxtzcepnfjmyalkupq","wdjbpfcewhuvjfqdyqeomfptuqxdtjiwwryjalbitkijkhkajglxgawkvesuydghfzxzirzgydyabooitxobgldmsfchxinipvaessorcxayxbdvvhnouqtkvbuyneywdhldhvkqsuwingpugklemgmvacrkekvpvnaulablvaumaabjvrevjovvrjtlvmifxnyneapwupvjnkmibzqvhkqbqykzavqlgkbqvljizesokmsjlmmoknjigk","mxsoakouqvnkljjnwmfhgrvoiqywsenlylepvzftaetslggakoeokkuxviicwhpbgijnlmddqehdeipbvxmhkymgvdlrvbkuvjgibbbibgfpnqabmwjolbwitfxazdhujmkvgmnunzxlvmkxpedukohwyevdijsjjodfrcyukqylwkqjevsbvzrrzviaqnuvyqsxgvvhjhgkaycvteqliaukaasmajqrxykatiwcolptpjabvykfauznvd","gvmooiuektkrevaxmiwbjaojashkbbmaglbmayhvqnvtwnydcvjgyppuuklvejqjrcbyzviabemqqntijvyglvxpjvkieuaydvgzzljvubfasavxxwvaugyomwpxjubksqkaveqdzrsvaxuwkdkdiqgxmnhwwpliabdondvjvflmsykljmeluhhbhtkegizqvhilkcomnpnqrkriufiwydjkfghgofnvcbjlfltyasrsqeodikokepxnzt","xnvkvtideprgzhqgbyzaobfqkkzkykawzssheivkukpugmamjgqkeffmyvjxlcatwxkhvvaskdnqhvjkginkaauihwtvpaiipdnugxboyjsljmngbxioryliaglqquukerywwboirwfhejyfmorsybbdaxagclnoobvlmmkjhnjwpivbmxynnfeuluvdevsuvjvilvdzavekjvxyvwrqltdjjtjlqmcbhqboieaqpukpsacoddtzvlemvg","fmjfhjgqitfbarfmehsgdgzmjkidukgkdobakbqybwqvohgshzbcemvwkvvqaitexovbjehlynuvvqeeqskswjrkmbwxmvualkfvbljgvxahkxnulikkkqirnpdupamhalpmwaodvxyejadvujsiriqglaagdaiyymailmjpfzvovnvyoosdllnwkjqglweyvrrhvestvpowccubnnxujjyxnqkuaicbbvzxkiiztpduvketljpyogyznt","djpeuvljthgqtuubiyvwoewgkjaevcmyurkubmcfxfakqwdueadtcvmajizpikvsmbvvihtosovzqxivqijsjndvayvkrgniqzpbamyjjanykktusjxjayonvygbahwjdsyshfzjlxwevxlnpwezlurokpbklgviioxszhvkmngqvgaxlfkokkxpbymarkeloolnabelmfrvdgaarkghypvbcdbvekmnifmuqlhdvjditiqbewhlqwnuqg","nbqdjymukphaefwnymugyovgauqixvwymjbjvkgninvcbvvxosjlmwmzdivwtfoydlgypilkwbgkaclyuviekhevidoolwbpveejxkqqsjeggisgkunvjkbmrlgthnofsqlvvpsaxopbltikaseruricezkmwazvfnqqvvgzfnsnaajdydduavozifjbbvxhdahylchjuxepjmxlujdrupwtkbibkyjxqkrlaraohhemzkktqkatmqviav","pefbijvvskonrajtmqwguektpjluvyykdvgjmakhoyeqweyfvbxhfvalsvkxgupwudlqlrnivtnztilxndvgrkyawkndloeypsmkjpdollmsikkmkuvjjzlagregagkxecvfhiygjdbhhmafxjiobmpaimvvobmeebykjekvqwauaqbvwtldsbisolbvwhqrziojvqzxvnoidqbaungrhmnqyicbjkaaatzjvygdcuipnqusfuxczwvxkh","arksvpqntqboagupaduhgjmqrvqgesljktgxllciygmlzqbuatoxrvjeajvybiznvvyvhajfvkclqvpnezijaocwooykbwnzkpikqhmnmadgilvvhnwyjyujjqgakfkwkxrdvuasswoleutoklgmfrixiypumlkwidlypkgepavvnkqbxsbwxsmznrtomcubyjiheblvkbnedeovfuvhkhvuqffdmiaixydevzkjgtbjdjvamwbeshadxi","sbeilghalvxbygvnpihgotwmyrxvgbhnlnqmkmsbavhaoivvnvdjqqvrueykjyktpwiiyuidqyxmuiwdcrjeizljekrhldfiapvzmopfekuokldbzxgvucvjnrynolhfdkxmgwpojcvtatalegfkgcgvakmqsamuwfqbovzyxjnevtbjsqioabljdujdwjvhvehkdksnemgskavafbuqvkseaqipbxkzlauijwwktqyzrjvykloaxupbnm","sobuexbmbiaxqmvviodjbjvpxkfvxnjejsvsdbnyktlakcutkynieokevehopvfgtlyzgwbayskqzvxhbaejlvvwlmrvkidxrnbybdandjyrjqndqvdsgainzgrqzsaeweflpjokhugujwavuuijwtfitfoyprmmwqtogahulsgommnvjyhraplkkvaqgdkeamzupkifavqvhiyakjpxhnkqikyquvzlovvwidcmlhbejgclxiuglmcbkw","riellsqyeiuqzjpapwvmpqyezartjhflvjwuqkvbfjuydbitkwypnnbksjbtjbaqiuazlewvdwbxevlndxpmlqgvmoyavavgaomyiokxuajyhagixcjdeisrvvakfsjknqehkhvkvmniwjgmevqhrnkpawlstkxfvoyudaznichgkbbdpditucrhtqehbxiagraxuikldnzlukvxfnkkjgmlksmsgoqvdmebvjgyclboomvwvfyogojuvz","xokkxyljivqbbiygkgmfndwvxuqblyamlwqosoqdrbeszrebkimgyvqytcdrvjkoiyrwvixeilstggjtvfvkbkmjkwlknkapumlhdzcvzhjzeaiigahhvasawhuqikeubavfnpbaoilorukmpfqxeadfjjvpazxkacthvgvxxynjjravlidcjsousbzewmpqgehlvounvvpyvvieushqgfelnvlgumaajdbmounnwqkdwttyjkdkpynmjb"};

class Solution {
public:
	
	template<typename T>
	using vector = std::vector<T>;
	using string = std::string;
    
    using high_resolution_clock = std::chrono::high_resolution_clock;
	using microseconds = std::chrono::microseconds;
	using milliseconds = std::chrono::milliseconds;
    using nanoseconds = std::chrono::nanoseconds;

	std::vector<nanoseconds> is_neighbor_durations{};
    std::vector<std::pair<int, nanoseconds>> is_neighbor_durations_2{};

    bool isNeighbor(string &a, string &b) {

        const auto t1 = high_resolution_clock::now();

        int diff = 0;
        for (int i = 0; i < a.size(); i++) {
            if (a[i] != b[i])
                if (++diff > 2) return false;
        }

        const auto t2 = high_resolution_clock::now();

        is_neighbor_durations.push_back(std::chrono::duration_cast<nanoseconds>(t2 - t1));

        return true;
    }
    int numSimilarGroups(vector<string>& strs) {
        int n = strs.size();

        if (strs[0].size() > 200)
        {
            return 0;
        }

        const auto t1 = high_resolution_clock::now();
        int counter{0};

        vector<vector<int>> g(n);
        for (int i = 0; i < n - 1; i++)
            for (int j = i+1; j < n; j++) {
                if (isNeighbor(strs[i], strs[j])) {
                    g[i].push_back(j);
                    g[j].push_back(i);
                }
                counter+=1;
            }

        const auto t2 = high_resolution_clock::now();

        is_neighbor_durations_2.push_back({counter, std::chrono::duration_cast<nanoseconds>(t2 - t1)});

        vector<bool> v(n, false);
        int ans = 0;
        for (int i = 0; i < n; i++) {
            if (v[i] == false) {
                dfs(g, v, i);
                ans++; // connected group count
            }
        }
        return ans;
    }

    void dfs(vector<vector<int>>& g, vector<bool>& v, int x) {
        v[x] = true;
        for (int adj: g[x])
            if (v[adj] == false)
                dfs(g, v, adj);
    } 
};


int main()
{

	Solution s;

	using std::chrono::high_resolution_clock;
	using std::chrono::microseconds;
	using std::chrono::milliseconds;
	using std::chrono::nanoseconds;

	int n{1'000'000};
	
	const auto t1 = high_resolution_clock::now();

	for (int i{0}; i < n; ++i)
	{
		s.numSimilarGroups(test_data);
	}

	const auto t2 = high_resolution_clock::now();

	const auto duration_us{std::chrono::duration_cast<microseconds>(t2 - t1)};
	const auto duration_ms{std::chrono::duration_cast<milliseconds>(t2 - t1)};

	double duration_per_run_us{static_cast<double>(duration_us.count()) / static_cast<double>(n)};

	std::cout << "duration per run [microseconds]: " << duration_per_run_us << std::endl;
	std::cout << "duration total [microseconds]: " << duration_ms.count() << std::endl;

    nanoseconds is_neighbor_sum{};

    for (const auto& duration : s.is_neighbor_durations)
    {
        is_neighbor_sum += duration;
    }

    std::cout << "isNeighbor total [nanoseconds]: " << is_neighbor_sum.count() << std::endl;

    nanoseconds is_neighbor_grouped_sum{};
    int total_invocation_count{0};
    
    for (const auto& count_duration_pair : s.is_neighbor_durations_2)
    {
        total_invocation_count += count_duration_pair.first;
        is_neighbor_grouped_sum += count_duration_pair.second;
    }

    std::cout << "isNeighbor total (grouped) [nanoseconds]: " << is_neighbor_grouped_sum.count() << std::endl;
    // std::cout << "isNeighbor total (grouped) [nanoseconds]: " << is_neighbor_sum << std::endl;

	return 0;
}
